import { Platform, StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  containerAreaSafe: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: Platform.OS === "ios" ? 50 : 0,
  },

  colors: {
    primary: { backgroundColor: "#0D6EFD" },
    secondary: { backgroundColor: "#6C757D" },
  },

  btnPrimary: {
    backgroundColor: "#0D6EFD",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnSecondary: {
    backgroundColor: "#6C757D",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnSuccess: {
    backgroundColor: "#198754",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnDanger: {
    backgroundColor: "#DC3545",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnWarning: {
    backgroundColor: "#FFC107",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnInfo: {
    backgroundColor: "#0DCAF0",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnLight: {
    backgroundColor: "#F8F9FA",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnDark: {
    backgroundColor: "#212529",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnLink: {
    color: "#689FEF",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },

  btnPrimaryBlock: {
    backgroundColor: "#0D6EFD",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnSecondaryBlock: {
    backgroundColor: "#6C757D",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnSuccessBlock: {
    backgroundColor: "#198754",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnDangerBlock: {
    backgroundColor: "#DC3545",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnWarningBlock: {
    backgroundColor: "#FFC107",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnInfoBlock: {
    backgroundColor: "#0DCAF0",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnLightBlock: {
    backgroundColor: "#F8F9FA",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  btnDarkBlock: {
    backgroundColor: "#212529",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  btnLinkBlock: {
    color: "#689FEF",
    padding: 8,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },

  textWhite: {
    color: "#FFFFFF",
    fontSize: 16,
  },
  textBlack: {
    color: "#000000ff",
    fontSize: 16,
  },
});
